### ISSUE TITLE
No default config, branding, environment variables

### ISSUE THREAD

**Issue by etfz** [dvtirol/pynetinstall#5]
Hi,

I don't know exactly what netinstall is capable of normally, but would it be possible to skip applying the default configuration after installation? And also install my custom branding package? Would the latter simply be a matter of uploading the package at the same time as the firmware?

Would it be possible to perhaps use environment variables instead of `pynetinstall.ini`?

About the boot images; do you know whether these ever change, or can I keep using the same ones "forever"?

**Comment by uedvt359** [comment]
> I don't know exactly what netinstall is capable of normally, but would it be possible to skip applying the default configuration after installation?

do you mean no config at all (i.e., "/export" is empty) or using the mikrotik default config instead of a custom one? the former can be done (although it seems ill-advised) by specifying an empty config.rsc. the latter can be done by not specifying a config at all.

> And also install my custom branding package? Would the latter simply be a matter of uploading the package at the same time as the firmware?

looking at [this screenshot](https://help.mikrotik.com/docs/download/attachments/24805390/netinstall_03.png), i think it should be possible to do this by extending `Flasher.do_files()` - i'd like to support this (if only i had the time). 

in our setup, we upload a default-config.rsc that:
1. uses /tool/fetch to download additional packages and the real (dynamcially generated) config.rsc
2. installs a on-startup scheduler that imports the config and removes itself
3. reboots the device (which installs the downloaded packages and triggers configuration)

> Would it be possible to perhaps use environment variables instead of pynetinstall.ini?

i don't know what use case you have in mind, but assuming you are trying to dynamically change which files to upload, you're supposed to write your own plugin that selects a routeros package and (optionally) default config based on mac address or model number (see readme). you can of course also write a small plugin that reads filenames from the environment.

**Comment by etfz** [comment]
Configuration question answered as per the other issue.

I tried simply copying the code that uploads the firmware package, adjusting the paths, and it seemed to work.

If you don't mind, roughly how do you work with your dynamic configuration system?

Regarding environment variables, I'm not sure that I had anything specific in mind, other than it being easier to edit than the ini file when using RouterOS. I saw the other open ticket with an example of a multi architecture plugin, and I'm certainly going to have a look at that, but I am going to need to figure out the values for some other architectures. What's an easy way of debugging that?

**Comment by uedvt359** [comment]
our workflow is like this (a little simplified):

1. we upload the firmware and a static stage0-config.rsc. 
2. this stage0-config.rsc then on first boot calls `/tool/fetch http://provisioning.internal/config?serial=abcdefgh dst-path=real-config.rsc` to download the actual config from a small api we wrote. 
3. then, stage0-config.rsc downloads packages (also with /tool/fetch) if needed and installs a `/system/scheduler start-time=startup on-event=/import real-config.rsc; /sys/scheduler/remove 0` and reboots. 
4. on reboot, the packages are installed and afterwards the config is imported and the scheduler removed.

the real-config.rsc is generated on the fly from jinja2 templates, with data provided by our dcim (data center infrastructure management) platform.

regarding values for other platforms: when you boot the netinstall image, pynetinstall will print out a line like this:

    Device found! mac=48:a9:8a:xx:xx:xx, model=RB5009UG+S+, arch=arm64

this should give you all the information you need. sadly, the model number listed here is often different than what /system/routerboard/print or /system/resource/print says, so you can't rely on that. for example, note the space in netinstall and no space in /sys/routerboard/print:

```
[INFO ] -> Device found! mac=xx:xx:xx:xx:xx:xx, model=RB LtAP-2HnD, arch=mmips

[xxx] > /sys router pr
        board-name: LtAP
             model: RBLtAP-2HnD

[xxx] > /sys resource pr
        architecture-name: mmips
               board-name: LtAP
                 platform: MikroTik
```

**Comment by etfz** [comment]
Hi again,

I've since written a deployment script of my own, and it works well, but I've realised that the provided script gets installed as default configuration, meaning it's basically impossible to reset the device to factory settings without using netinstall again. Do you have any solution in place for this, or do you just leave it like that?

One option that looked promising was forgoing the netinstall script, and instead packaging it into a branding package as default configuration, which is executed automatically upon installing the package. You may subsequently install the factory configuration as the default by installing a branding package without a default configuration script. However this script does not seem to run when the branding package is installed by netinstall. netinstall has these options that I would like to try, but I don't know whether pynetinstall supports them, nor how I would use them:

> -r - When the reinstallation process is performed, the current configuration will be reset, and for devices that have it, the default configuration will be applied (optional).
> -e - Performing the reinstallation process will reset the device to an empty configuration.

**Comment by uedvt359** [comment]
your observations are correct. in case we want to reset a device to factory defaults, we remove it from our dcim. because our pynetinstall plugin uses the dcim database to select which firmware and config to install to a device, if it can't find it, it uploads some random 7.x firmware with config=None. this re-installs the factory config and is equivalent to `-r`.

if i understand `-e` correctly, it can be done by setting config to a file containing just a newline, as we figured out in bug 4. i haven't done any packet traces to confirm that this is equivalent, though.

**Comment by etfz** [comment]
Thanks. It seems like it works doing it via a branding package instead. Just need to perform a few more tests. I'm not too good with Python; how do I use the new feature of returning multiple packages from my plugin?

On an unrelated note, I've noticed the container takes ten seconds to stop on my MikroTik. I wanna say it didn't take that long at first, but I don't know for sure. I don't seem to get any debug output indicating any issues. Do you know why this would be?

**Comment by uedvt359** [comment]
> how do I use the new feature of returning multiple packages from my plugin?

in `get_files`: `return my_firmware, my_package1, my_package2, my_config`. if you have a list of packages, `return my_firmware, *my_list_of_packages, my_config` (note the `*`).

> I've noticed the container takes ten seconds to stop on my MikroTik.

i'm expeciencing the same thing over here. i haven't debugged it, but i've adopted the habit of issuing `/container stop 0; :while [/container find status=stopping] do={}; /container start 0`. this busy-loops until the container is killed and  starts it afterwards again.

**Comment by etfz** [comment]
Thanks. I got it working, and it seems to still work with branding packages.

I looked into the shutdown thing and, as far as I understand, the ten seconds is just a timeout as the container waits for the entrypoint to terminate gracefully, which doesn't happen due to the container dispatching a `SIGTERM` signal rather than `SIGINT` (keyboard interrupt) when stopping. One could handle the `SIGTERM` signal:

https://stackoverflow.com/questions/53852681/python-inside-docker-container-gracefully-stop

As a workaround, I found that you can also force RouterOS to dispatch `SIGINT` when stopping the container by setting its stop signal to 2. This makes the script terminate properly.
https://faculty.cs.niu.edu/~hutchins/csci480/signals.htm

**Comment by uedvt359** [comment]
> which doesn't happen due to the container dispatching a SIGTERM signal rather than SIGINT (keyboard interrupt) when stopping

ohhh! https://raby.sh/sigterm-and-pid-1-why-does-a-container-linger-after-receiving-a-sigterm.html
i was expecting SIG_DFL to kill the process on sigterm, but pid 1 doesn't automatically get that handler installed. 

fixed in ebf0244b954a43fbcf90842e8648e98aaa47c2b0

**Comment by etfz** [comment]
Great!

I don't think have any reason to keep this issue open any longer, so I will close it.

I will just attach my attempt at a plugin. It does automatic architecture selection, allows specifying a branding package, and uses environment variables. Some existing files would need to be edited in order to allow using a environment variable for plugin selection, too, but I've not bothered with that, for now.

```python
import os

from io import BufferedReader
from configparser import ConfigParser

from pynetinstall.interface import InterfaceInfo

arch_name = {
    "mips": "mipsbe"
}

class Plugin:
    """
    This is the setup of the Default Plugin

    The Plugin takes at least one argument to save the config to (`config`)
    It includes the Configuration of the programm loaded from the file (config.ini)

    Attributes
    ----------

    config : ConfigParser
        The Configuration loaded from `config.ini`

    Methods
    -------

    get_files(info) -> tuple[BufferedReader, BufferedReader]
        Get a Reader object of the npk and the rsc file

    Raises
    ------

    KeyError
        A File is not defined in the configuration
    ValueError
        A File does not exist
    """
    def __init__(self, config: ConfigParser):
        self.firmware_version = os.getenv("FIRMWARE_VERSION")
        self.default_config = os.getenv("CONFIG_FILE")
        self.branding_package = os.getenv("BRANDING_PACKAGE")

        if not self.firmware_version:
            raise KeyError(f"[pynetinstall]FIRMWARE_VERSION is not defined in the environment")
        if self.default_config and not os.path.exists(self.default_config):
            raise ValueError(f"The config file {self.default_config!r} does not exist")
        if self.branding_package and not os.path.exists(self.branding_package):
            raise ValueError(f"The branding package {self.branding_package!r} does not exist")

    def get_files(self, info: InterfaceInfo) -> tuple[BufferedReader, BufferedReader]:
        """
        Searches for the path of the .npk and .rsc files in the config

        Arguments
        ---------

        info : InterfaceInfo
            Information about the Device (MAC Address, Model, Architecture, min OS, Licence)

        Returns
        -------

         - (BufferedReader or str or None, BufferedReader or str or None):
           Tuple of the path or URL to the .npk and the .rsc file
           (ROUTEROS.npk, CONFIG.rsc), or a file handle to them.
           If firmware is None, an error is assumed. If config is None, only
           the firmware will be installed.
        """

        arch = arch_name[info.arch] if info.arch in arch_name else info.arch

        firmware = f"data/packages/routeros-{self.firmware_version}-{arch}.npk"

        if not os.path.exists(firmware):
            raise ValueError(f"The firmware file {firmware!r} does not exist")

        default_config_h = open(self.default_config, "rb") if self.default_config else None

        packages = []

        if self.branding_package:
            packages.append(open(self.branding_package, "rb"))

        return open(firmware, "rb"), *packages, default_config_h
```

**Comment by uedvt359** [comment]
On Tue, 2024-12-03 at 00:25 -0800, etfz wrote:

Great!

I don't think have any reason to keep this issue open any longer, so I will close it.

I will just attach my attempt at a plugin. It does automatic architecture selection, allows specifying a branding package, and uses environment variables.

looks great! i see where you're going with environment vars, nice to see it's working out for you.

Some existing files would need to be edited in order to allow using a environment variable for plugin selection, too, but I've not bothered with that, for now.

i think the current approach should suffice. if you want to make a docker container that is configured though environ vars, you'll need to ship a plugin like yours anyways with the container. and then, a static one-liner .ini selecting that plugin can just be shipped as well.
